### ISSUE TITLE
Document how the ramdisk is created

### ISSUE THREAD

**Issue by probonopd** [darwin-on-arm/ramdisk#1]
Please document how the ramdisk is created, e.g., post the script that puts it together.

**Comment by b-man** [comment]
On Linux you need to do the following to create and access the image:

```
sudo apt-get install hfsplus hfsprogs
dd if=/dev/zero of=./ramdisk.dmg bs=1M count=32
mkfs.hfsplus ./ramdisk.dmg
mkdir ./tmp
sudo mount -t hfsplus -o loop ./ramdisk.dmg ./tmp
```

On OSX you need to do the following to create and access the image:

```
hdiutil create ./ramdisk.dmg -type UDIF -size 32m -fs JHFS+ -volname "Ramdisk"
sudo open ./ramdisk.dmg
```

The contents of the image are based on a modified ios 4.3.2 ramdisk. This will change once we are able to build userspace components.

**Comment by b-man** [comment]
I'll go ahead and add this to the wiki.

**Comment by b-man** [comment]
New wiki page can be found here: https://github.com/darwin-on-arm/wiki/wiki/Creating-a-new-ramdisk

**Comment by probonopd** [comment]
Thanks!
